# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('precio_venta', models.FloatField(max_length=50)),
                ('precio_promo', models.FloatField(max_length=50)),
                ('fecha_terminacion', models.DateField()),
                ('descripcion', models.TextField(max_length=100)),
                ('imagen_articulo', models.FileField(upload_to='imagenes/')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
                'ordering': ['nombre_articulo'],
            },
        ),
    ]
