# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('POP', 'Popayan'), ('CAL', 'Cali'), ('PAS', 'Pasto'), ('PER', 'Pereira'), ('CAQ', 'Caqueta'), ('SAN', 'Santander'), ('TAM', 'Tambo')], max_length=20)),
                ('nombre_punto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='puntos')),
            ],
            options={
                'verbose_name_plural': 'PuntosVentas',
                'ordering': ['nombre_punto'],
            },
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archive',
            field=models.FileField(upload_to='docuementos/'),
        ),
    ]
